export interface CommandDoc {
  /** 命令的整体作用(没匹配到具体子命令时使用) */
  summary: string
  /** 子命令 -> 说明,例如 git 的 commit / push,docker 的 run / build */
  subcommands?: Record<string, string>
  /** 参数(短选项已展开,如 -rf 会拆成 -r 和 -f) -> 说明 */
  flags?: Record<string, string>
}

// 本地命令知识库:覆盖常见 Linux/Unix/DevOps 命令,不依赖网络即可解释命令含义。
// 按类别分组,方便后续增补。
export const COMMAND_DOCS: Record<string, CommandDoc> = {
  // ------------------------- 文件与目录操作 -------------------------
  ls: {
    summary: '列出目录内容',
    flags: {
      '-l': '以长格式显示(权限、所有者、大小、时间等)',
      '-a': '显示所有文件,包括隐藏文件(以 . 开头)',
      '-h': '以易读格式显示文件大小(如 1K、234M)',
      '-t': '按修改时间排序',
      '-r': '反向排序',
      '-R': '递归列出子目录',
      '-S': '按文件大小排序',
      '-d': '只列出目录本身而非其内容',
      '-1': '每行只显示一个文件',
      '--color': '用颜色区分文件类型',
    },
  },
  cd: { summary: '切换当前工作目录' },
  pwd: { summary: '打印当前工作目录的绝对路径' },
  cp: {
    summary: '复制文件或目录',
    flags: {
      '-r': '递归复制目录',
      '-R': '递归复制目录',
      '-f': '强制覆盖,不询问',
      '-i': '覆盖前询问确认',
      '-v': '显示详细过程',
      '-p': '保留原文件的权限、时间戳等属性',
      '-a': '归档模式,等价于保留属性并递归复制',
      '-n': '不覆盖已存在的文件',
      '-u': '仅当源文件较新时才复制',
    },
  },
  mv: {
    summary: '移动或重命名文件/目录',
    flags: {
      '-f': '强制覆盖,不询问',
      '-i': '覆盖前询问确认',
      '-v': '显示详细过程',
      '-n': '不覆盖已存在的文件',
    },
  },
  rm: {
    summary: '删除文件或目录',
    flags: {
      '-r': '递归删除目录及其内容',
      '-R': '递归删除目录及其内容',
      '-f': '强制删除,不提示、忽略不存在的文件',
      '-i': '删除前逐一确认',
      '-v': '显示删除过程',
      '-d': '删除空目录',
    },
  },
  mkdir: {
    summary: '创建目录',
    flags: { '-p': '按需创建多级父目录,目录已存在也不报错', '-v': '显示创建过程', '-m': '创建时指定权限模式' },
  },
  rmdir: { summary: '删除空目录', flags: { '-p': '递归删除空的父目录' } },
  touch: { summary: '创建空文件,或更新已有文件的修改时间', flags: { '-a': '仅更新访问时间', '-m': '仅更新修改时间' } },
  cat: {
    summary: '打印文件内容到终端(也常用于拼接文件)',
    flags: { '-n': '显示行号', '-A': '显示所有不可见字符', '-b': '仅对非空行显示行号', '-s': '压缩连续空行' },
  },
  tac: { summary: '倒序打印文件内容(从最后一行开始)' },
  less: { summary: '分页查看文件内容,可上下翻页、搜索(比 more 功能更强)' },
  more: { summary: '分页查看文件内容(只能向下翻页)' },
  head: {
    summary: '显示文件开头部分内容(默认前 10 行)',
    flags: { '-n': '指定显示的行数', '-c': '指定显示的字节数' },
  },
  tail: {
    summary: '显示文件末尾部分内容(默认后 10 行),常用于查看日志',
    flags: { '-n': '指定显示的行数', '-f': '持续监视文件末尾新增内容(常用于跟踪日志)', '-c': '指定显示的字节数' },
  },
  find: {
    summary: '在目录树中按条件查找文件',
    flags: {
      '-name': '按文件名匹配(支持通配符)',
      '-iname': '按文件名匹配,忽略大小写',
      '-type': '按类型过滤(f 文件 / d 目录 / l 软链接)',
      '-mtime': '按修改时间过滤(单位:天)',
      '-size': '按文件大小过滤',
      '-exec': '对找到的文件执行指定命令',
      '-delete': '删除找到的文件',
      '-maxdepth': '限制搜索的目录深度',
    },
  },
  locate: { summary: '基于预先建立的索引快速查找文件路径(比 find 快,但依赖定期更新的数据库)' },
  updatedb: { summary: '手动更新 locate 命令使用的文件索引数据库' },
  tree: { summary: '以树状结构显示目录层级', flags: { '-L': '限制显示的层级深度', '-a': '显示隐藏文件', '-d': '只显示目录' } },
  du: {
    summary: '统计文件/目录占用的磁盘空间',
    flags: {
      '-h': '以易读格式显示大小(K/M/G)',
      '-s': '只显示总计,不展开子目录',
      '-a': '同时显示文件(默认只统计目录)',
      '--max-depth': '限制统计的目录深度',
    },
  },
  df: { summary: '显示磁盘/分区的空间使用情况', flags: { '-h': '以易读格式显示大小', '-T': '同时显示文件系统类型', '-i': '显示 inode 使用情况' } },
  ln: { summary: '创建链接(默认硬链接)', flags: { '-s': '创建软链接(符号链接),而非硬链接', '-f': '强制覆盖已存在的链接' } },
  chmod: {
    summary: '修改文件或目录的权限',
    flags: {
      '-R': '递归修改目录下所有内容的权限',
      '-v': '显示修改过程',
      '777': '所有人(自己/同组/其他)都拥有读写执行权限,通常权限过大存在风险',
      '755': '自己可读写执行,其他人只能读和执行',
      '644': '自己可读写,其他人只能读',
    },
  },
  chown: { summary: '修改文件或目录的所有者(以及所属组)', flags: { '-R': '递归修改目录下所有内容的所有者', '-v': '显示修改过程' } },
  chgrp: { summary: '修改文件或目录的所属组', flags: { '-R': '递归修改' } },
  stat: { summary: '显示文件或文件系统的详细元信息(大小、权限、inode、时间戳等)' },
  file: { summary: '识别文件的实际类型(基于内容而非扩展名)' },
  wc: { summary: '统计文本的行数/单词数/字节数', flags: { '-l': '只统计行数', '-w': '只统计单词数', '-c': '只统计字节数', '-m': '只统计字符数' } },
  basename: { summary: '从路径中提取文件名部分(去掉目录)' },
  dirname: { summary: '从路径中提取目录部分(去掉文件名)' },
  realpath: { summary: '解析并显示文件的绝对路径(会解析软链接)' },
  readlink: { summary: '显示符号链接指向的实际路径', flags: { '-f': '递归解析到最终的真实路径' } },
  rsync: {
    summary: '高效地同步/复制文件(增量传输,常用于备份和远程同步)',
    flags: {
      '-a': '归档模式,保留权限、时间戳等并递归复制',
      '-v': '显示详细过程',
      '-z': '传输时压缩数据',
      '-r': '递归复制目录',
      '--delete': '删除目标中源里已不存在的文件,保持完全一致',
      '-P': '显示进度并支持断点续传',
      '-n': '演练模式,只显示会做什么但不真正执行',
    },
  },
  scp: { summary: '通过 SSH 在本地和远程主机间复制文件', flags: { '-r': '递归复制目录', '-P': '指定远程 SSH 端口', '-i': '指定使用的私钥文件' } },
  sftp: { summary: '通过 SSH 建立交互式文件传输会话' },
  install: { summary: '复制文件并同时设置权限/所有者,常用于安装脚本' },
  shred: { summary: '反复覆写文件内容后删除,防止数据被恢复(不可逆销毁)' },
  wipefs: { summary: '擦除磁盘/分区上的文件系统签名,擦除后该分区的文件系统标识会消失' },

  // ------------------------- 压缩与归档 -------------------------
  tar: {
    summary: '打包/解包文件(常配合压缩使用)',
    flags: {
      '-c': '创建新归档',
      '-x': '解开归档',
      '-t': '列出归档内容而不解压',
      '-z': '同时用 gzip 压缩/解压(.tar.gz)',
      '-j': '同时用 bzip2 压缩/解压(.tar.bz2)',
      '-J': '同时用 xz 压缩/解压(.tar.xz)',
      '-v': '显示处理过程中的文件名',
      '-f': '指定归档文件名',
      '-C': '解压/打包时先切换到指定目录',
    },
  },
  zip: { summary: '将文件压缩打包为 .zip', flags: { '-r': '递归压缩目录', '-e': '压缩时加密', '-9': '使用最高压缩率' } },
  unzip: { summary: '解压 .zip 文件', flags: { '-l': '只列出压缩包内容不解压', '-d': '指定解压目标目录', '-o': '解压时覆盖已存在文件不询问' } },
  gzip: { summary: '压缩文件为 .gz 格式(压缩后原文件会被替换)', flags: { '-d': '解压', '-k': '压缩/解压后保留原文件', '-9': '最高压缩率' } },
  gunzip: { summary: '解压 .gz 文件' },
  bzip2: { summary: '压缩文件为 .bz2 格式(压缩率比 gzip 高但更慢)', flags: { '-d': '解压' } },
  bunzip2: { summary: '解压 .bz2 文件' },
  xz: { summary: '压缩文件为 .xz 格式(压缩率通常最高)', flags: { '-d': '解压', '-k': '保留原文件' } },
  unxz: { summary: '解压 .xz 文件' },
  '7z': { summary: '压缩/解压 7z 格式及多种其他压缩格式', subcommands: { a: '添加文件到压缩包', x: '解压(保留目录结构)', l: '列出压缩包内容' } },

  // ------------------------- 文本处理 -------------------------
  grep: {
    summary: '在文件或输入中按模式搜索匹配的行',
    flags: {
      '-r': '递归搜索目录下所有文件',
      '-R': '递归搜索(跟随符号链接)',
      '-i': '忽略大小写',
      '-v': '反向匹配,显示不匹配的行',
      '-n': '显示匹配行的行号',
      '-l': '只列出包含匹配内容的文件名',
      '-c': '只统计匹配的行数',
      '-E': '使用扩展正则表达式',
      '-o': '只输出匹配到的部分,而非整行',
      '-A': '同时显示匹配行之后的若干行',
      '-B': '同时显示匹配行之前的若干行',
      '-w': '按整词匹配',
    },
  },
  egrep: { summary: '使用扩展正则表达式搜索文本(等价于 grep -E)' },
  fgrep: { summary: '按普通字符串(非正则)搜索文本(等价于 grep -F)' },
  sed: {
    summary: '流式文本编辑器,常用于按规则替换/删除文本',
    flags: { '-i': '直接修改源文件(而非只输出到终端)', '-n': '取消默认输出,配合 p 命令按需打印', '-e': '指定要执行的编辑脚本', '-E': '使用扩展正则表达式' },
  },
  awk: { summary: '按列/字段处理结构化文本,可编写脚本进行统计和格式化', flags: { '-F': '指定字段分隔符', '-v': '向脚本传入变量' } },
  cut: { summary: '从每行中提取指定的列或字符', flags: { '-d': '指定字段分隔符', '-f': '指定要提取的字段编号', '-c': '按字符位置提取' } },
  sort: {
    summary: '对文本行进行排序',
    flags: { '-n': '按数值大小排序而非字典序', '-r': '倒序排序', '-u': '排序后去除重复行', '-k': '按指定字段排序', '-t': '指定字段分隔符' },
  },
  uniq: { summary: '去除相邻的重复行(通常配合 sort 使用)', flags: { '-c': '统计每行出现的次数', '-d': '只显示重复的行', '-u': '只显示不重复的行' } },
  tr: { summary: '对字符进行替换/删除/压缩(逐字符处理,不是整行)', flags: { '-d': '删除指定字符', '-s': '将连续重复字符压缩为一个' } },
  xargs: { summary: '把标准输入的内容转换为命令行参数,传给后面的命令执行', flags: { '-I': '指定占位符,用于将输入插入命令的任意位置', '-n': '每次传给命令的参数个数', '-P': '并发执行的进程数' } },
  tee: { summary: '将标准输入同时写入文件和标准输出(常用于一边执行一边保存日志)', flags: { '-a': '追加到文件末尾而不是覆盖' } },
  diff: { summary: '比较两个文件的差异', flags: { '-u': '以统一格式(unified diff)显示差异', '-r': '递归比较两个目录', '-i': '比较时忽略大小写' } },
  patch: { summary: '根据 diff 生成的补丁文件,把改动应用到原文件上' },
  cmp: { summary: '逐字节比较两个文件是否相同' },
  comm: { summary: '逐行比较两个已排序文件,分三列显示各自独有和共有的行' },
  join: { summary: '按公共字段连接两个已排序文件的内容(类似数据库 join)' },
  paste: { summary: '按行合并多个文件的内容(横向拼接)' },
  split: { summary: '将大文件切分成多个小文件' },
  fold: { summary: '将长行按指定宽度自动换行' },
  fmt: { summary: '简单地重新排版文本段落' },
  column: { summary: '把输入内容按列对齐显示,便于阅读' },
  jq: { summary: '命令行 JSON 处理器,用于提取/过滤/格式化 JSON 数据' },
  yq: { summary: '命令行 YAML 处理器,用法类似 jq' },
  printf: { summary: '按格式模板输出文本(比 echo 更精确可控)' },
  echo: { summary: '在终端输出一段文字', flags: { '-n': '输出后不换行', '-e': '解析反斜杠转义字符(如 \\n)' } },

  // ------------------------- 进程与系统监控 -------------------------
  ps: { summary: '查看当前系统中的进程列表', flags: { '-e': '显示所有进程', '-f': '显示完整格式信息', '-aux': '显示所有用户的详细进程信息(BSD 风格)', '-ef': '显示所有进程的完整信息(System V 风格)' } },
  top: { summary: '实时动态显示系统资源占用和进程排名' },
  htop: { summary: '交互式、彩色的进程查看器(top 的增强版)' },
  kill: { summary: '向指定进程发送信号(默认 SIGTERM,请求进程正常退出)', flags: { '-9': '发送 SIGKILL,强制立即终止进程,进程无法处理该信号', '-15': '发送 SIGTERM,请求进程正常退出(默认信号)', '-l': '列出所有可用信号名称' } },
  killall: { summary: '按进程名批量发送信号终止进程(可能一次性影响多个同名进程)', flags: { '-9': '强制终止' } },
  pkill: { summary: '按名称或其他条件匹配并终止进程', flags: { '-9': '强制终止', '-f': '匹配完整命令行而不只是进程名' } },
  pgrep: { summary: '按名称或条件查找进程 ID' },
  nice: { summary: '以指定的调度优先级启动一个新进程' },
  renice: { summary: '调整正在运行进程的调度优先级' },
  jobs: { summary: '列出当前 shell 会话中的后台任务' },
  bg: { summary: '将暂停的任务放到后台继续运行' },
  fg: { summary: '将后台任务切换到前台运行' },
  nohup: { summary: '让命令忽略挂断信号,在终端关闭后继续运行' },
  disown: { summary: '将任务从当前 shell 的任务列表中移除,使其不受终端关闭影响' },
  systemctl: {
    summary: '管理 systemd 系统服务(启动/停止/查看状态等)',
    subcommands: {
      start: '启动指定的服务',
      stop: '停止指定的服务',
      restart: '重启指定的服务',
      reload: '重新加载服务配置而不完全重启',
      status: '查看服务的运行状态',
      enable: '设置服务开机自启',
      disable: '取消服务开机自启',
      'list-units': '列出当前已加载的单元',
      'daemon-reload': '重新加载 systemd 配置',
    },
  },
  service: { summary: '管理系统服务(较旧的 init 脚本方式,systemd 系统上通常转发给 systemctl)' },
  journalctl: { summary: '查看 systemd 的日志记录', flags: { '-u': '只看指定服务的日志', '-f': '持续跟踪最新日志', '-n': '显示最后 N 行', '--since': '按起始时间过滤' } },
  uptime: { summary: '显示系统已运行时间、当前负载等信息' },
  free: { summary: '显示系统内存使用情况', flags: { '-h': '以易读格式显示大小', '-m': '以 MB 为单位显示', '-g': '以 GB 为单位显示' } },
  vmstat: { summary: '报告虚拟内存、进程、CPU 等系统整体统计信息' },
  iostat: { summary: '报告 CPU 和磁盘 I/O 的统计信息' },
  mpstat: { summary: '报告各 CPU 核心的使用率统计' },
  lsof: { summary: '列出当前系统打开的文件(含网络连接),常用于排查端口占用', flags: { '-i': '只显示网络相关的文件描述符(端口占用等)', '-p': '只显示指定进程打开的文件' } },
  strace: { summary: '跟踪进程执行时发出的系统调用,用于调试底层行为' },
  ltrace: { summary: '跟踪进程调用的动态库函数,用于调试' },
  watch: { summary: '按固定间隔重复执行一个命令并刷新显示结果' },
  time: { summary: '统计一个命令执行所花费的时间' },
  timeout: { summary: '限定一个命令的最长运行时间,超时后自动终止' },
  crontab: { summary: '管理定时任务计划(cron)', flags: { '-e': '编辑当前用户的定时任务', '-l': '列出当前用户的定时任务', '-r': '删除当前用户的所有定时任务' } },
  at: { summary: '安排一个命令在将来某个时间点执行一次' },

  // ------------------------- 网络 -------------------------
  ping: { summary: '向目标主机发送 ICMP 请求,测试网络连通性和延迟', flags: { '-c': '指定发送的请求次数', '-i': '指定发送间隔' } },
  curl: {
    summary: '发起 HTTP/FTP 等网络请求,常用于调试接口或下载文件',
    flags: {
      '-X': '指定请求方法(GET/POST 等)',
      '-H': '添加请求头',
      '-d': '发送 POST 数据',
      '-o': '将响应内容保存到文件',
      '-O': '以远程文件名保存到本地',
      '-L': '跟随重定向',
      '-s': '静默模式,不显示进度条',
      '-I': '只获取响应头',
      '-k': '忽略 SSL 证书校验(不安全,慎用)',
      '-v': '显示详细的请求/响应过程',
    },
  },
  wget: { summary: '从网络下载文件', flags: { '-O': '指定保存的文件名', '-r': '递归下载(常用于下载整个网站)', '-c': '断点续传', '-q': '静默模式' } },
  ssh: { summary: '通过 SSH 协议登录远程主机或执行远程命令', flags: { '-p': '指定远程端口', '-i': '指定使用的私钥文件', '-L': '建立本地端口转发', '-N': '不执行远程命令,仅建立连接(常配合端口转发)' } },
  netstat: { summary: '显示网络连接、路由表、端口监听等信息(较旧,推荐用 ss)', flags: { '-t': '只显示 TCP 连接', '-u': '只显示 UDP 连接', '-l': '只显示监听中的端口', '-n': '不解析主机名/服务名,直接显示数字', '-p': '显示对应的进程' } },
  ss: { summary: '显示网络连接和端口监听信息(netstat 的现代替代品)', flags: { '-t': '只显示 TCP', '-u': '只显示 UDP', '-l': '只显示监听中的端口', '-n': '不解析服务名', '-p': '显示对应的进程' } },
  ifconfig: { summary: '查看或配置网络接口信息(较旧,推荐用 ip)' },
  ip: {
    summary: '查看或配置网络接口、路由、地址等(现代网络管理工具)',
    subcommands: { addr: '查看/管理 IP 地址', link: '查看/管理网络接口状态', route: '查看/管理路由表', a: '查看 IP 地址(addr 简写)', r: '查看路由表(route 简写)' },
  },
  iptables: { summary: '配置 Linux 内核防火墙规则', flags: { '-L': '列出当前规则', '-F': '清空所有规则(可能导致原有防护失效)', '-A': '在链末尾追加一条规则', '-D': '删除一条规则', '-P': '设置链的默认策略' } },
  ufw: { summary: 'Ubuntu 上简化版防火墙管理工具', subcommands: { enable: '启用防火墙', disable: '关闭防火墙(会失去防护)', status: '查看防火墙状态', allow: '放行某端口/服务', deny: '拒绝某端口/服务' } },
  'firewall-cmd': { summary: 'firewalld 防火墙的管理命令(CentOS/RHEL 常见)' },
  nmap: { summary: '网络扫描工具,用于探测主机存活、开放端口和服务' },
  traceroute: { summary: '显示数据包到达目标主机所经过的每一跳路由' },
  mtr: { summary: '结合 ping 和 traceroute,持续监测到目标的路由和丢包情况' },
  dig: { summary: '查询 DNS 记录(比 nslookup 更详细)' },
  nslookup: { summary: '查询域名对应的 IP 地址(DNS 查询)' },
  host: { summary: '简单查询域名的 DNS 记录' },
  telnet: { summary: '建立到指定主机端口的纯文本连接,常用于简单测试端口是否可达' },
  nc: { summary: '网络瑞士军刀,可用于端口扫描、建立连接、传输数据等', flags: { '-l': '进入监听模式', '-v': '显示详细过程', '-z': '仅扫描端口是否开放,不发送数据' } },
  ncat: { summary: 'nc 的增强版本(nmap 项目自带)' },
  arp: { summary: '查看或修改本机的 ARP 缓存表(IP 与 MAC 地址映射)' },
  route: { summary: '查看或修改系统路由表(较旧,推荐用 ip route)' },
  hostname: { summary: '显示或设置本机的主机名' },

  // ------------------------- 包管理 -------------------------
  apt: { summary: 'Debian/Ubuntu 系统的软件包管理工具', subcommands: { install: '安装软件包', remove: '卸载软件包(保留配置文件)', purge: '卸载软件包并删除配置文件', update: '更新可用软件包的索引信息', upgrade: '升级已安装的软件包', search: '搜索软件包', list: '列出软件包' } },
  'apt-get': { summary: 'Debian/Ubuntu 系统的软件包管理工具(apt 的底层实现)', subcommands: { install: '安装软件包', remove: '卸载软件包', update: '更新软件包索引', upgrade: '升级已安装的软件包' } },
  'apt-cache': { summary: '查询 apt 软件包索引信息(如搜索、查看依赖)' },
  dpkg: { summary: '直接操作 .deb 软件包(比 apt 更底层)', flags: { '-i': '安装 .deb 包', '-r': '卸载软件包(保留配置)', '-l': '列出已安装的包', '-L': '列出某个包安装了哪些文件' } },
  yum: { summary: 'CentOS/RHEL 系统的软件包管理工具(较旧版本)', subcommands: { install: '安装软件包', remove: '卸载软件包', update: '更新软件包', search: '搜索软件包' } },
  dnf: { summary: 'CentOS/RHEL/Fedora 现代软件包管理工具(yum 的继任者)', subcommands: { install: '安装软件包', remove: '卸载软件包', update: '更新软件包' } },
  rpm: { summary: '直接操作 .rpm 软件包(比 yum/dnf 更底层)', flags: { '-i': '安装软件包', '-e': '卸载软件包', '-q': '查询软件包信息' } },
  pacman: { summary: 'Arch Linux 的软件包管理工具', flags: { '-S': '安装软件包', '-R': '卸载软件包', '-Syu': '同步并升级全部软件包', '-Q': '查询已安装的包' } },
  brew: { summary: 'macOS/Linux 上的 Homebrew 包管理工具', subcommands: { install: '安装软件包', uninstall: '卸载软件包', update: '更新 Homebrew 自身及软件源信息', upgrade: '升级已安装的软件包', search: '搜索软件包', list: '列出已安装的包' } },
  snap: { summary: 'Ubuntu 的 Snap 沙盒软件包管理工具', subcommands: { install: '安装软件包', remove: '卸载软件包', list: '列出已安装的包' } },
  npm: {
    summary: 'Node.js 包管理工具',
    subcommands: {
      install: '安装依赖包(不带包名时安装 package.json 里的全部依赖)',
      i: '安装依赖包(install 的简写)',
      uninstall: '卸载依赖包',
      run: '执行 package.json 中定义的脚本',
      start: '执行 start 脚本,通常用于启动项目',
      test: '执行测试脚本',
      build: '执行构建脚本',
      publish: '发布包到 npm 仓库',
      ci: '严格按照 lock 文件安装依赖,常用于 CI 环境',
      init: '初始化一个新的 package.json',
      update: '更新依赖到允许范围内的最新版本',
    },
  },
  pnpm: { summary: '高效的 Node.js 包管理工具(节省磁盘空间、速度更快)', subcommands: { install: '安装依赖', add: '添加一个依赖包', remove: '移除一个依赖包', run: '执行脚本', build: '执行构建脚本' } },
  yarn: { summary: 'Node.js 包管理工具(Facebook 出品)', subcommands: { install: '安装依赖', add: '添加一个依赖包', remove: '移除一个依赖包', run: '执行脚本' } },
  pip: { summary: 'Python 包管理工具', subcommands: { install: '安装 Python 包', uninstall: '卸载 Python 包', list: '列出已安装的包', freeze: '导出当前环境已安装包及版本' } },
  pip3: { summary: 'Python 3 包管理工具(用法同 pip)', subcommands: { install: '安装 Python 包', uninstall: '卸载 Python 包', list: '列出已安装的包' } },
  gem: { summary: 'Ruby 包管理工具', subcommands: { install: '安装 gem 包', uninstall: '卸载 gem 包', list: '列出已安装的 gem' } },
  cargo: { summary: 'Rust 的包管理与构建工具', subcommands: { build: '编译项目', run: '编译并运行项目', test: '运行测试', install: '安装一个二进制 crate' } },
  go: { summary: 'Go 语言工具链', subcommands: { build: '编译代码', run: '编译并运行代码', get: '下载并安装依赖包', test: '运行测试', mod: '管理 go.mod 依赖模块' } },
  composer: { summary: 'PHP 的包依赖管理工具', subcommands: { install: '按 lock 文件安装依赖', update: '更新依赖到最新允许版本', require: '添加一个依赖包' } },

  // ------------------------- 版本控制 -------------------------
  git: {
    summary: 'Git 版本控制工具',
    subcommands: {
      init: '初始化一个新的 Git 仓库',
      clone: '克隆一个远程仓库到本地',
      add: '将改动加入暂存区,准备提交',
      commit: '将暂存区的改动提交为一个版本',
      push: '把本地提交推送到远程仓库',
      pull: '从远程仓库拉取并合并最新改动',
      fetch: '从远程仓库获取最新数据,但不自动合并',
      merge: '将其他分支的改动合并到当前分支',
      rebase: '将当前分支的提交历史"重放"到另一个基础之上,会改写提交历史',
      branch: '查看、创建或删除分支',
      checkout: '切换分支或恢复文件到某个版本',
      switch: '切换分支(checkout 的更明确替代命令)',
      status: '查看当前工作区和暂存区的状态',
      log: '查看提交历史',
      diff: '查看文件改动的具体内容',
      reset: '回退版本或撤销暂存,--hard 会丢弃未提交的改动,不可恢复',
      stash: '临时保存当前未提交的改动,方便切换分支后再恢复',
      tag: '给某个提交打标签(常用于标记版本号)',
      remote: '查看或管理远程仓库地址',
      'cherry-pick': '将某个特定提交单独应用到当前分支',
      revert: '生成一个新提交,用于撤销之前某次提交的改动(不改写历史,更安全)',
      config: '配置 Git 的用户信息、别名等设置',
      show: '查看某个提交的详细内容',
      blame: '逐行查看文件每一行是谁在哪次提交中修改的',
      clean: '删除工作区中未被 Git 跟踪的文件,-f 强制执行、-d 包含目录',
    },
  },
  svn: { summary: 'Subversion 版本控制工具', subcommands: { checkout: '检出一个仓库到本地', update: '更新到最新版本', commit: '提交改动', add: '将文件加入版本控制', status: '查看改动状态' } },
  hg: { summary: 'Mercurial 版本控制工具(用法与 git 类似)' },

  // ------------------------- 容器与编排 -------------------------
  docker: {
    summary: 'Docker 容器管理工具',
    subcommands: {
      run: '基于镜像创建并启动一个新容器',
      build: '根据 Dockerfile 构建一个新镜像',
      ps: '列出正在运行的容器(-a 显示所有,含已停止的)',
      images: '列出本地已有的镜像',
      exec: '在正在运行的容器内执行命令(常用于进入容器排查问题)',
      logs: '查看容器的日志输出',
      stop: '停止一个正在运行的容器',
      start: '启动一个已停止的容器',
      restart: '重启容器',
      rm: '删除一个或多个容器(容器需先停止)',
      rmi: '删除一个或多个镜像',
      pull: '从镜像仓库拉取镜像',
      push: '将镜像推送到镜像仓库',
      inspect: '查看容器/镜像的详细底层信息',
      network: '管理 Docker 网络',
      volume: '管理 Docker 数据卷',
      compose: '基于 docker-compose.yml 管理多容器应用',
      cp: '在容器和宿主机之间复制文件',
      tag: '给镜像打标签',
      prune: '清理停止的容器/未使用的镜像等,释放磁盘空间',
    },
  },
  'docker-compose': { summary: '基于 YAML 文件管理多容器应用', subcommands: { up: '创建并启动所有服务(-d 后台运行)', down: '停止并删除所有服务的容器、网络', logs: '查看服务日志', ps: '列出服务状态', build: '构建服务镜像', restart: '重启服务' } },
  podman: { summary: '与 Docker 命令兼容的容器管理工具(无需常驻守护进程)', subcommands: { run: '创建并启动一个新容器', ps: '列出容器', build: '构建镜像', exec: '在容器内执行命令' } },
  kubectl: {
    summary: 'Kubernetes 集群管理命令行工具',
    subcommands: {
      get: '查看资源列表(如 pod、service、deployment)',
      apply: '按 YAML 文件创建或更新资源',
      delete: '删除指定的资源',
      describe: '查看某个资源的详细信息和事件',
      logs: '查看 Pod 的日志',
      exec: '在容器内执行命令',
      create: '创建资源',
      rollout: '管理发布/回滚过程',
      scale: '调整副本数量',
      'port-forward': '将本地端口转发到集群内的 Pod',
    },
  },
  helm: { summary: 'Kubernetes 的包管理工具(Chart 管理)', subcommands: { install: '安装一个 Chart', upgrade: '升级已安装的 Release', uninstall: '卸载一个 Release', list: '列出已安装的 Release' } },

  // ------------------------- 用户与权限 -------------------------
  sudo: { summary: '以超级用户(root)权限执行后面的命令,操作影响范围更大,请确认命令内容', flags: { '-i': '以 root 身份启动一个登录 shell', '-u': '以指定用户身份执行命令' } },
  su: { summary: '切换到另一个用户身份(默认切到 root)', flags: { '-': '切换用户并加载该用户的完整登录环境' } },
  useradd: { summary: '创建一个新的系统用户', flags: { '-m': '同时创建用户的家目录', '-s': '指定用户的登录 shell', '-G': '将用户加入附加组' } },
  userdel: { summary: '删除一个系统用户', flags: { '-r': '同时删除该用户的家目录和邮件池' } },
  usermod: { summary: '修改已存在用户的属性(如所属组、shell等)', flags: { '-aG': '将用户追加到指定附加组(不影响原有组)', '-s': '修改用户的登录 shell' } },
  groupadd: { summary: '创建一个新的用户组' },
  passwd: { summary: '修改用户密码' },
  groups: { summary: '显示指定用户所属的所有用户组' },
  id: { summary: '显示用户的 UID、GID 及所属组信息' },
  whoami: { summary: '显示当前登录的用户名' },
  who: { summary: '显示当前登录系统的所有用户' },
  w: { summary: '显示当前登录用户及其正在执行的操作' },
  last: { summary: '显示系统的登录历史记录' },
  visudo: { summary: '安全地编辑 sudoers 权限配置文件(带语法检查)' },

  // ------------------------- 磁盘与文件系统 -------------------------
  mount: { summary: '将文件系统挂载到指定目录', flags: { '-a': '挂载 /etc/fstab 中列出的所有文件系统', '-t': '指定文件系统类型', '-o': '指定挂载选项' } },
  umount: { summary: '卸载(解除挂载)一个文件系统', flags: { '-f': '强制卸载' } },
  fdisk: { summary: '查看或修改磁盘的分区表(交互式,操作分区有风险)', flags: { '-l': '列出所有磁盘的分区信息' } },
  parted: { summary: '查看或修改磁盘分区表(支持更大磁盘和更多文件系统)' },
  mkfs: { summary: '在指定设备上创建文件系统(格式化),会清空该设备原有数据' },
  mke2fs: { summary: '创建 ext2/3/4 文件系统(格式化),会清空原有数据' },
  fsck: { summary: '检查并修复文件系统的错误' },
  dd: { summary: '按块复制/转换数据,常用于制作镜像、克隆磁盘,操作裸设备时风险极高', flags: { if: '指定输入文件/设备', of: '指定输出文件/设备,若指向磁盘设备可能覆盖其全部数据', bs: '指定每次读写的块大小' } },
  lsblk: { summary: '以树状结构列出所有块设备(磁盘、分区)' },
  blkid: { summary: '显示块设备的文件系统类型和 UUID 等信息' },
  losetup: { summary: '将文件关联为一个回环(loop)设备,常用于挂载镜像文件' },
  swapon: { summary: '启用一个交换分区/文件' },
  swapoff: { summary: '禁用一个交换分区/文件' },

  // ------------------------- 电源与系统管理 -------------------------
  shutdown: { summary: '关闭系统,会中断所有正在运行的服务和进程', flags: { '-h': '关机', '-r': '重启', now: '立即执行' } },
  reboot: { summary: '立即重启系统,会中断所有正在运行的服务和进程' },
  halt: { summary: '停止系统运行(部分系统上等同于关机)' },
  poweroff: { summary: '关闭系统电源' },
  init: { summary: '切换系统运行级别,init 0 关机、init 6 重启(较旧的系统管理方式)' },

  // ------------------------- 编辑器 -------------------------
  vim: { summary: '功能强大的文本编辑器(模式化操作:普通/插入/命令模式)' },
  vi: { summary: '经典文本编辑器(vim 的前身,多数系统里 vi 即 vim)' },
  nano: { summary: '简单易上手的命令行文本编辑器' },
  emacs: { summary: '功能强大、高度可扩展的文本编辑器' },

  // ------------------------- Shell / 环境 -------------------------
  export: { summary: '设置环境变量,并使其对后续启动的子进程可见' },
  unset: { summary: '删除一个 shell 变量或环境变量' },
  alias: { summary: '为命令创建一个简短的别名' },
  unalias: { summary: '删除一个已定义的别名' },
  source: { summary: '在当前 shell 中执行脚本文件(不新开子进程,可影响当前环境)' },
  history: { summary: '显示当前 shell 的历史命令记录' },
  which: { summary: '显示某个命令对应的可执行文件所在路径' },
  whereis: { summary: '查找命令的可执行文件、源码和帮助文档所在位置' },
  type: { summary: '显示某个名称是内置命令、别名还是外部可执行文件' },
  man: { summary: '查看命令的官方使用手册' },
  env: { summary: '显示当前所有环境变量,或在指定环境下执行命令' },
  printenv: { summary: '显示环境变量的值' },
  set: { summary: '显示或设置 shell 选项和变量' },
  read: { summary: '从标准输入读取一行内容并赋值给变量' },
  eval: { summary: '将字符串作为命令重新解析并执行' },
  exec: { summary: '用指定命令替换当前 shell 进程(不会创建新的子进程)' },
  chsh: { summary: '修改用户的默认登录 shell' },

  // ------------------------- 系统信息 -------------------------
  date: { summary: '显示或设置系统日期和时间', flags: { '+%Y-%m-%d': '按指定格式显示日期' } },
  cal: { summary: '显示日历' },
  uname: { summary: '显示系统内核和硬件架构信息', flags: { '-a': '显示全部系统信息' } },
  arch: { summary: '显示当前系统的硬件架构' },
  lscpu: { summary: '显示 CPU 架构相关的详细信息' },
  lsusb: { summary: '列出系统识别到的 USB 设备' },
  lspci: { summary: '列出系统识别到的 PCI 设备' },
  dmidecode: { summary: '显示硬件的 DMI/SMBIOS 信息(主板、内存条型号等)' },
  hostnamectl: { summary: '查看或设置主机名及相关系统信息' },
  timedatectl: { summary: '查看或设置系统时间、时区、NTP 同步状态' },

  // ------------------------- 其他常用 -------------------------
  clear: { summary: '清空当前终端屏幕显示' },
  exit: { summary: '退出当前 shell 会话' },
  logout: { summary: '注销当前登录会话' },
  reset: { summary: '重置终端显示状态(当终端显示错乱时可用)' },
  screen: { summary: '终端复用工具,可创建持久化的终端会话,断开连接后任务继续运行' },
  tmux: { summary: '终端复用工具(screen 的现代替代),支持多窗口/多面板' },
}
