export interface NetworkPhraseDoc {
  /** 空格分隔的命令关键词前缀(不含具体参数值,如接口名、IP、名称等) */
  phrase: string
  /** 适用厂商/平台,用于在解读里标注来源 */
  vendor: string
  summary: string
}

// 网络设备命令知识库:交换机/防火墙/无线控制器等,命令结构以"多词短语"为主,
// 和 Unix 工具的"动词 + 短选项"结构不同,单独维护、单独匹配(见 localExplain.ts 的 matchNetworkPhrase)。
export const NETWORK_DEVICE_DOCS: NetworkPhraseDoc[] = [
  // ===================== 华为 / H3C VRP(交换机通用;USG 防火墙同一命令体系) =====================
  { phrase: 'system-view', vendor: '华为/H3C VRP', summary: '从用户视图进入系统视图,开始全局配置' },
  { phrase: 'sys', vendor: '华为/H3C VRP', summary: 'system-view 的简写,进入系统视图' },
  { phrase: 'quit', vendor: '华为/H3C VRP', summary: '退出当前视图,回到上一级视图' },
  { phrase: 'return', vendor: '华为/H3C VRP', summary: '直接返回用户视图(不管当前处于哪一级视图)' },
  { phrase: 'save', vendor: '华为/H3C VRP', summary: '把当前运行配置保存为启动配置,断电/重启后依然生效' },
  { phrase: 'undo', vendor: '华为/H3C VRP', summary: '撤销/删除紧跟其后的这条配置命令' },
  { phrase: 'display current-configuration', vendor: '华为/H3C VRP', summary: '显示当前生效的完整配置' },
  { phrase: 'display current-configuration interface', vendor: '华为/H3C VRP', summary: '显示指定接口当前的配置' },
  { phrase: 'display saved-configuration', vendor: '华为/H3C VRP', summary: '显示上一次保存的启动配置' },
  { phrase: 'display this', vendor: '华为/H3C VRP', summary: '只显示当前视图下生效的配置片段' },
  { phrase: 'display interface', vendor: '华为/H3C VRP', summary: '显示接口的详细状态和流量统计信息' },
  { phrase: 'display interface brief', vendor: '华为/H3C VRP', summary: '简要显示所有接口的状态(链路/协议是否 up 等)' },
  { phrase: 'display ip interface brief', vendor: '华为/H3C VRP', summary: '简要显示各接口的 IP 地址和状态' },
  { phrase: 'display ip routing-table', vendor: '华为/H3C VRP', summary: '显示 IP 路由表' },
  { phrase: 'display version', vendor: '华为/H3C VRP', summary: '显示设备型号、软件版本等信息' },
  { phrase: 'display device', vendor: '华为/H3C VRP', summary: '显示设备槽位、单板运行状态' },
  { phrase: 'display vlan', vendor: '华为/H3C VRP', summary: '显示 VLAN 配置和端口归属情况' },
  { phrase: 'display mac-address', vendor: '华为/H3C VRP', summary: '显示 MAC 地址表' },
  { phrase: 'display arp', vendor: '华为/H3C VRP', summary: '显示 ARP 表项(IP 与 MAC 地址映射)' },
  { phrase: 'display cpu-usage', vendor: '华为/H3C VRP', summary: '显示 CPU 使用率' },
  { phrase: 'display memory-usage', vendor: '华为/H3C VRP', summary: '显示内存使用情况' },
  { phrase: 'display logbuffer', vendor: '华为/H3C VRP', summary: '显示日志缓冲区中的历史日志' },
  { phrase: 'display users', vendor: '华为/H3C VRP', summary: '显示当前登录设备的用户会话' },
  { phrase: 'display ospf peer', vendor: '华为/H3C VRP', summary: '显示 OSPF 邻居状态' },
  { phrase: 'display ospf lsdb', vendor: '华为/H3C VRP', summary: '显示 OSPF 链路状态数据库' },
  { phrase: 'display bgp peer', vendor: '华为/H3C VRP', summary: '显示 BGP 对等体连接状态' },
  { phrase: 'display stp', vendor: '华为/H3C VRP', summary: '显示生成树协议(STP/RSTP/MSTP)状态,排查二层环路' },
  { phrase: 'display trunk', vendor: '华为/H3C VRP', summary: '显示链路聚合(Eth-Trunk)组的状态' },
  { phrase: 'display port vlan', vendor: '华为/H3C VRP', summary: '显示各端口所属的 VLAN 及链路类型' },
  { phrase: 'interface', vendor: '华为/H3C VRP', summary: '进入指定接口视图,后续命令只对该接口生效' },
  { phrase: 'interface vlanif', vendor: '华为/H3C VRP', summary: '进入 VLAN 虚接口视图,给该 VLAN 配置三层 IP 地址(网关)' },
  { phrase: 'interface eth-trunk', vendor: '华为/H3C VRP', summary: '进入链路聚合口视图,把多条物理链路捆绑成一条逻辑链路' },
  { phrase: 'vlan', vendor: '华为/H3C VRP', summary: '创建并进入指定 VLAN 视图' },
  { phrase: 'vlan batch', vendor: '华为/H3C VRP', summary: '一次性批量创建多个 VLAN' },
  { phrase: 'ip address', vendor: '华为/H3C VRP', summary: '给当前接口配置 IP 地址和子网掩码' },
  { phrase: 'port link-type', vendor: '华为/H3C VRP', summary: '设置端口类型:access(接入)/ trunk(干道)/ hybrid(混合)' },
  { phrase: 'port default vlan', vendor: '华为/H3C VRP', summary: '设置 access 端口所属的默认 VLAN' },
  { phrase: 'port trunk allow-pass vlan', vendor: '华为/H3C VRP', summary: '设置 trunk 端口放行哪些 VLAN 的流量' },
  { phrase: 'shutdown', vendor: '华为/H3C VRP', summary: '在接口视图下关闭当前接口' },
  { phrase: 'undo shutdown', vendor: '华为/H3C VRP', summary: '开启当前接口(很多接口默认是关闭状态,需要手动开启)' },
  { phrase: 'ospf', vendor: '华为/H3C VRP', summary: '创建/进入 OSPF 进程视图,配置 OSPF 动态路由协议' },
  { phrase: 'bgp', vendor: '华为/H3C VRP', summary: '创建/进入 BGP 协议视图' },
  { phrase: 'vrrp', vendor: '华为/H3C VRP', summary: '配置 VRRP 虚拟路由冗余协议,实现网关高可用' },
  { phrase: 'stp enable', vendor: '华为/H3C VRP', summary: '开启生成树协议,防止二层网络出现广播风暴环路' },
  { phrase: 'dhcp enable', vendor: '华为/H3C VRP', summary: '开启设备的 DHCP 服务功能' },
  { phrase: 'acl', vendor: '华为/H3C VRP', summary: '创建/进入 ACL(访问控制列表)视图,定义流量匹配规则' },
  { phrase: 'nat', vendor: '华为/H3C VRP', summary: '配置 NAT 地址转换(常见于出口路由器/USG 防火墙)' },
  { phrase: 'nat server', vendor: '华为 USG', summary: '配置 NAT 服务器映射(端口映射),把外网请求转发到内网服务器' },
  { phrase: 'nat-policy', vendor: '华为 USG', summary: '配置 NAT 转换策略(新版本 USG 用策略化方式管理 NAT 规则)' },
  { phrase: 'security-policy', vendor: '华为 USG', summary: '进入安全策略视图,配置安全区域之间的访问控制规则' },
  { phrase: 'security-zone', vendor: '华为 USG', summary: '进入安全区域视图(如 trust/untrust/dmz),管理接口与安全域的绑定' },
  { phrase: 'firewall zone', vendor: '华为 USG', summary: '创建/进入防火墙安全区域' },
  { phrase: 'display security-policy', vendor: '华为 USG', summary: '显示当前配置的安全策略规则' },
  { phrase: 'display firewall session table', vendor: '华为 USG', summary: '显示防火墙当前的会话表(连接跟踪表),排查连通性问题' },
  { phrase: 'display zone', vendor: '华为 USG', summary: '显示安全区域及其包含的接口' },
  { phrase: 'ips', vendor: '华为 USG', summary: '配置入侵防御(IPS)相关功能' },
  { phrase: 'av', vendor: '华为 USG', summary: '配置防病毒(AV)相关功能' },
  { phrase: 'aaa', vendor: '华为/H3C VRP', summary: '进入 AAA 视图,配置认证、授权、计费和本地用户' },
  { phrase: 'local-user', vendor: '华为/H3C VRP', summary: '创建本地用户账号(用于登录设备或接入认证)' },
  { phrase: 'ssh user', vendor: '华为/H3C VRP', summary: '配置允许通过 SSH 登录设备的用户' },
  { phrase: 'telnet', vendor: '华为/H3C VRP', summary: '通过 Telnet 登录其他设备(明文协议,建议改用 SSH)' },
  { phrase: 'ping', vendor: '华为/H3C VRP', summary: '测试到目标地址的网络连通性(用法和 Linux ping 类似)' },
  { phrase: 'tracert', vendor: '华为/H3C VRP', summary: '显示到目标地址经过的每一跳路由(相当于 Linux 的 traceroute)' },
  { phrase: 'reboot', vendor: '华为/H3C VRP', summary: '重启设备' },
  { phrase: 'reset saved-configuration', vendor: '华为/H3C VRP', summary: '清空启动配置(下次重启将恢复出厂配置),操作不可逆' },
  { phrase: 'sysname', vendor: '华为/H3C VRP', summary: '设置设备的主机名' },
  { phrase: 'super password', vendor: 'H3C VRP', summary: '设置进入特权模式(system-view)所需的密码' },
  { phrase: 'commit', vendor: '华为/H3C VRP', summary: '提交候选配置使其生效(部分新版本设备采用两阶段配置模式)' },

  // ===================== Fortinet FortiGate(FortiOS) =====================
  { phrase: 'config system interface', vendor: 'FortiGate', summary: '进入接口配置块,管理各接口的 IP、角色等参数' },
  { phrase: 'config system global', vendor: 'FortiGate', summary: '进入全局系统设置块(主机名、管理端口等)' },
  { phrase: 'config system dns', vendor: 'FortiGate', summary: '配置设备使用的 DNS 服务器' },
  { phrase: 'config system admin', vendor: 'FortiGate', summary: '配置管理员账号' },
  { phrase: 'config system dhcp server', vendor: 'FortiGate', summary: '配置 DHCP 服务器' },
  { phrase: 'config firewall policy', vendor: 'FortiGate', summary: '进入防火墙策略配置块,定义流量放行/拒绝规则' },
  { phrase: 'config firewall address', vendor: 'FortiGate', summary: '配置地址对象(供防火墙策略引用)' },
  { phrase: 'config firewall addrgrp', vendor: 'FortiGate', summary: '配置地址组对象' },
  { phrase: 'config firewall vip', vendor: 'FortiGate', summary: '配置虚拟 IP(端口映射/DNAT),把外网访问转发到内网服务器' },
  { phrase: 'config router static', vendor: 'FortiGate', summary: '配置静态路由' },
  { phrase: 'config router bgp', vendor: 'FortiGate', summary: '配置 BGP 动态路由' },
  { phrase: 'config router ospf', vendor: 'FortiGate', summary: '配置 OSPF 动态路由' },
  { phrase: 'config vpn ipsec phase1-interface', vendor: 'FortiGate', summary: '配置 IPsec VPN 第一阶段(IKE)参数' },
  { phrase: 'config vpn ipsec phase2-interface', vendor: 'FortiGate', summary: '配置 IPsec VPN 第二阶段(加密流量选择)参数' },
  { phrase: 'config user local', vendor: 'FortiGate', summary: '配置本地用户账号(供认证策略使用)' },
  { phrase: 'config antivirus profile', vendor: 'FortiGate', summary: '配置防病毒检测策略模板' },
  { phrase: 'config webfilter profile', vendor: 'FortiGate', summary: '配置网页过滤策略模板' },
  { phrase: 'edit', vendor: 'FortiGate', summary: '在当前 config 配置块内新建/编辑一个具名条目,进入其子配置' },
  { phrase: 'set', vendor: 'FortiGate', summary: '在当前 edit 条目内设置某个参数的值' },
  { phrase: 'unset', vendor: 'FortiGate', summary: '把某个参数恢复为默认值' },
  { phrase: 'next', vendor: 'FortiGate', summary: '结束当前 edit 条目并可继续编辑下一个,不退出整个 config 块' },
  { phrase: 'end', vendor: 'FortiGate', summary: '结束并退出当前 config 配置块,使改动生效' },
  { phrase: 'show', vendor: 'FortiGate', summary: '显示当前生效的配置(只显示和默认值不同的部分,较精简)' },
  { phrase: 'show full-configuration', vendor: 'FortiGate', summary: '显示完整配置,包括所有默认值参数' },
  { phrase: 'get system status', vendor: 'FortiGate', summary: '查看设备型号、固件版本、序列号等系统状态' },
  { phrase: 'get system interface', vendor: 'FortiGate', summary: '查看接口列表及其状态' },
  { phrase: 'get system performance status', vendor: 'FortiGate', summary: '查看 CPU、内存等性能状态' },
  { phrase: 'get router info routing-table all', vendor: 'FortiGate', summary: '查看完整路由表' },
  { phrase: 'diagnose sys top', vendor: 'FortiGate', summary: '类似 Linux 的 top,实时查看进程资源占用情况' },
  { phrase: 'diagnose debug flow', vendor: 'FortiGate', summary: '开启流量调试跟踪,用于排查策略命中和转发问题' },
  { phrase: 'diagnose ip address list', vendor: 'FortiGate', summary: '列出设备各接口当前实际生效的 IP 地址' },
  { phrase: 'diagnose firewall session list', vendor: 'FortiGate', summary: '列出当前防火墙会话(连接跟踪)表' },
  { phrase: 'diagnose sniffer packet', vendor: 'FortiGate', summary: '设备自带抓包工具,按接口和过滤条件捕获报文' },
  { phrase: 'execute ping', vendor: 'FortiGate', summary: '从设备本身发起 ping 测试连通性' },
  { phrase: 'execute traceroute', vendor: 'FortiGate', summary: '从设备本身发起路由跟踪' },
  { phrase: 'execute reboot', vendor: 'FortiGate', summary: '重启设备' },
  { phrase: 'execute backup config', vendor: 'FortiGate', summary: '把当前配置备份到指定位置(如 U 盘/FTP/TFTP)' },
  { phrase: 'execute restore config', vendor: 'FortiGate', summary: '从备份文件恢复配置' },

  // ===================== MikroTik RouterOS(路径式命令,以 / 开头) =====================
  { phrase: '/ip address print', vendor: 'RouterOS', summary: '查看已配置的接口 IP 地址列表' },
  { phrase: '/ip address add', vendor: 'RouterOS', summary: '给接口新增一个 IP 地址' },
  { phrase: '/ip address remove', vendor: 'RouterOS', summary: '删除一条已配置的 IP 地址' },
  { phrase: '/interface print', vendor: 'RouterOS', summary: '查看所有接口列表及其状态' },
  { phrase: '/interface ethernet print', vendor: 'RouterOS', summary: '查看以太网口的详细信息' },
  { phrase: '/interface wireless print', vendor: 'RouterOS', summary: '查看无线接口配置' },
  { phrase: '/interface bridge print', vendor: 'RouterOS', summary: '查看网桥(二层桥接组)配置' },
  { phrase: '/ip route print', vendor: 'RouterOS', summary: '查看路由表' },
  { phrase: '/ip route add', vendor: 'RouterOS', summary: '添加一条静态路由' },
  { phrase: '/ip firewall filter print', vendor: 'RouterOS', summary: '查看防火墙过滤规则(类似 Linux iptables 的 filter 表)' },
  { phrase: '/ip firewall nat print', vendor: 'RouterOS', summary: '查看 NAT 转换规则' },
  { phrase: '/ip firewall address-list print', vendor: 'RouterOS', summary: '查看地址列表(供防火墙规则引用的 IP 分组)' },
  { phrase: '/ip dhcp-server print', vendor: 'RouterOS', summary: '查看 DHCP 服务器配置' },
  { phrase: '/ip dhcp-client print', vendor: 'RouterOS', summary: '查看 DHCP 客户端(接口自动获取地址)配置' },
  { phrase: '/ip service print', vendor: 'RouterOS', summary: '查看设备开放的管理服务(如 telnet/ssh/www 端口)' },
  { phrase: '/ip hotspot print', vendor: 'RouterOS', summary: '查看热点(Hotspot 认证上网)配置' },
  { phrase: '/system resource print', vendor: 'RouterOS', summary: '查看 CPU、内存、存储等系统资源使用情况' },
  { phrase: '/system identity print', vendor: 'RouterOS', summary: '查看设备名称(identity)' },
  { phrase: '/system identity set', vendor: 'RouterOS', summary: '设置设备名称' },
  { phrase: '/system routerboard print', vendor: 'RouterOS', summary: '查看 RouterBoard 硬件信息(型号、序列号等)' },
  { phrase: '/system reboot', vendor: 'RouterOS', summary: '重启设备' },
  { phrase: '/system backup save', vendor: 'RouterOS', summary: '把当前配置保存为二进制备份文件' },
  { phrase: '/export', vendor: 'RouterOS', summary: '把当前配置导出为可读脚本文件(常用于备份/迁移配置)' },
  { phrase: '/user print', vendor: 'RouterOS', summary: '查看本地管理用户列表' },
  { phrase: '/user add', vendor: 'RouterOS', summary: '新增一个管理用户' },
  { phrase: '/log print', vendor: 'RouterOS', summary: '查看系统日志' },
  { phrase: '/ping', vendor: 'RouterOS', summary: '测试到目标地址的连通性' },
  { phrase: '/tool torch', vendor: 'RouterOS', summary: '实时监控接口上按 IP/协议/端口分类的流量,用于流量分析排障' },
  { phrase: '/queue simple print', vendor: 'RouterOS', summary: '查看简单队列(限速规则)配置' },
  { phrase: '/routing bgp print', vendor: 'RouterOS', summary: '查看 BGP 路由协议配置' },
  { phrase: '/certificate print', vendor: 'RouterOS', summary: '查看已导入/生成的证书列表' },
  { phrase: '/ip', vendor: 'RouterOS', summary: 'IP 相关配置路径的根节点(地址/路由/防火墙/DHCP 等都在此路径下)' },
  { phrase: '/interface', vendor: 'RouterOS', summary: '接口相关配置路径的根节点' },
  { phrase: '/system', vendor: 'RouterOS', summary: '系统相关配置路径的根节点(资源/身份/备份/重启等)' },

  // ===================== Aruba(无线控制器 AC / 瘦 AP,ArubaOS) =====================
  { phrase: 'show ap database', vendor: 'Aruba AC', summary: '查看已注册到控制器的 AP 列表及其状态' },
  { phrase: 'show ap active', vendor: 'Aruba AC', summary: '查看当前在线(活跃)的 AP' },
  { phrase: 'show ap association', vendor: 'Aruba AC', summary: '查看关联到各 AP 的无线客户端' },
  { phrase: 'show user-table', vendor: 'Aruba AC', summary: '查看当前接入的无线用户会话表' },
  { phrase: 'show ip interface brief', vendor: 'Aruba AC', summary: '简要显示各接口的 IP 地址和状态' },
  { phrase: 'show interface', vendor: 'Aruba AC', summary: '显示接口详细状态和流量统计' },
  { phrase: 'show running-config', vendor: 'Aruba AC', summary: '显示当前生效的运行配置' },
  { phrase: 'show version', vendor: 'Aruba AC', summary: '显示设备型号和软件版本信息' },
  { phrase: 'show switches', vendor: 'Aruba AC', summary: '在 Mobility Master 架构下查看被管理的控制器列表' },
  { phrase: 'show wlan ssid-profile', vendor: 'Aruba AC', summary: '查看 SSID 配置模板(名称、加密方式等)' },
  { phrase: 'show ap-group', vendor: 'Aruba AC', summary: '查看 AP 组配置(一组 AP 共用同一套策略模板)' },
  { phrase: 'configure terminal', vendor: 'Aruba AC', summary: '进入全局配置模式' },
  { phrase: 'wlan ssid-profile', vendor: 'Aruba AC', summary: '创建/进入 SSID 配置模板,设置无线网络名称和认证加密方式' },
  { phrase: 'wlan virtual-ap', vendor: 'Aruba AC', summary: '创建/进入虚拟 AP 模板,将 SSID 与转发方式、VLAN 等关联' },
  { phrase: 'ap-group', vendor: 'Aruba AC', summary: '创建/进入 AP 组,批量下发配置给一批 AP' },
  { phrase: 'ap-name', vendor: 'Aruba AC', summary: '按名称进入某台具体 AP 的单独配置' },
  { phrase: 'write memory', vendor: 'Aruba AC', summary: '把当前运行配置保存为启动配置(断电重启后依然生效)' },
  { phrase: 'reload', vendor: 'Aruba AC', summary: '重启设备' },

  // ===================== 通用:display / show 输出过滤修饰符(多个厂商都支持类似语法) =====================
  { phrase: 'include', vendor: '通用(display/show 输出过滤)', summary: '配合管道 | 使用,只显示包含指定关键字的行' },
  { phrase: 'exclude', vendor: '通用(display/show 输出过滤)', summary: '配合管道 | 使用,排除包含指定关键字的行' },
  { phrase: 'begin', vendor: '通用(display/show 输出过滤)', summary: '配合管道 | 使用,从第一次出现关键字的行开始显示' },
  { phrase: 'count', vendor: '通用(display/show 输出过滤)', summary: '配合管道 | 使用,统计上一条命令输出的行数' },
]
